# Generated by Django 4.1.2 on 2022-10-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('Grocery', 'Grocery'), ('Travel', 'Travel'), ('Sports', 'Sports'), ('Office', 'Office'), ('Food', 'Food'), ('Weekend Plan', 'Weekend Plan'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
