# Generated by Django 4.1.2 on 2022-10-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_date_note_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='time',
        ),
    ]
